theme: jekyll-theme-cayman
title: [Team Asians + Jye]
description: [ELEC4403 Group Project]

nav:
    - {title: 所有文章, description: archive, url: '/archive'}   
    - {title: 标签, description: tags, url: '/tags'}   
    - {title: 留言, description: liuyan, url: '/liuyan'}
    - {title: 资源, description: ziyuan, url: '/ziyuan'}
    - {title: 关于我, description: about, url: '/about'}
